server:
  port: 8200

spring:
  application:
    name: link-preview-service
  # 레디스 설정
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
      # Lettuce 설정
      lettuce:
        pool:
          max-active: 32  # 동시 연결 수 증가
          max-idle: 32
          min-idle: 8

metadata:
  extractor:
    timeout: 5000  # 요청 타임아웃 (ms)
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"  # 크롬 User-Agent
    max-retries: 3  # 최대 재시도 횟수
    retry-delay: 1000  # 재시도 간격 (ms)
  cache:
    duration: 24h  # 캐시 유효 기간

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25